### ISSUE TITLE
Set-TerraformWorkspace does not always find workspaces 

### ISSUE THREAD

**Issue by richclement** [smastrorocco/terraposh#7]
Set-TerraformWorkspace uses `terraform workspace list` to find the workspace that matches the current git branch. It appears to look across all workspaces in the configured backend. If another git repository has the branch name and workspace `bug-fix-1` and the current repository is on branch `bug-fix` then the function will not realize it needs to make a new workspace.

LIne 179 to use a regex to match the current branch name in the list of workspaces. It does not appear to do a full match so in the above example, when on branch `bug-fix` the regex matches the previous workspace of `bug-fix-1`. The code then attempts to select the `bug-fix` workspace and it fails.

I am not sure about a solution for this other than forcing an exact match. However, I am also not sure what the consequences are of using the same terraform workspace across multiple repositories in the scenario that you are working on two repositories to fix a problem and have the same branch name in both.

**Comment by smastrorocco** [comment]
Thanks @richclement.  Workspaces are unique to:

- A backend, in this case S3
- A terraform state file, or in this case the S3 key

If you have multiple repos that point at unique S3 keys in a single bucket, this should be safe to have the same workspace.  However, the regex, does appear to be a bug and I'll address that.

**Comment by smastrorocco** [comment]
@richclement Please pull down the branch from PR #8 which should resolve your issue.  If it does, I'll merge it.
